name: tests-windows-caching

on: push


jobs:
  test-windows:
    env:
      POETRY_CACHE_DIR: ~/.cache/pypoetry
    defaults:
      run:
        shell: bash
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: ./
        with:
          version: 1.1.4
          virtualenvs-create: false
      - uses: actions/cache@v2
        id: cached-venv
        with:
          path: ~/.cache
          key: test-windows-cache-${{ hashFiles('**/poetry.lock') }}-2
      - run: poetry install --no-interaction --no-root -vvv
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - run: |
          pytest --version